workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

image: python:3.10.2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"


cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - apt-get update
  - apt-get install -y clang-format git
  - python --version
  - python -m venv .venv/
  - source .venv/bin/activate
  - python -m pip install --upgrade pip
  - pip install cpplint

stages:
  - lint
  - desktop-build

lint-job:
  stage: lint
  script:
    - chmod -R +x ci/run_lint.sh
    - ./ci/run_lint.sh

desktop-sim-job:
  stage: desktop-build
  script:
    - apt-get install -y --no-install-recommends make cmake g++ gcc python3-pip python3
    - pip install Jinja2
    - chmod -R +x ci/build_desktop.sh
    - ./ci/build_desktop.sh
