/*
 * board_config_types.h
 */

#ifndef COMMON_DEVICES_COMMON_BOARD_CONFIG_TYPES_H_
#define COMMON_DEVICES_COMMON_BOARD_CONFIG_TYPES_H_

#define RADIO_TI_TYPE_CC1120 1
#define RADIO_TI_TYPE_CC1200 2

#endif  // COMMON_DEVICES_COMMON_BOARD_CONFIG_TYPES_H_
