################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_calibrate.cpp \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_config.cpp \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_erase_flash.cpp \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_help.cpp \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_main.cpp \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_offload.cpp \
/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_sense.cpp 

OBJS += \
./System/States/Cli/state_cli_calibrate.o \
./System/States/Cli/state_cli_config.o \
./System/States/Cli/state_cli_erase_flash.o \
./System/States/Cli/state_cli_help.o \
./System/States/Cli/state_cli_main.o \
./System/States/Cli/state_cli_offload.o \
./System/States/Cli/state_cli_sense.o 

CPP_DEPS += \
./System/States/Cli/state_cli_calibrate.d \
./System/States/Cli/state_cli_config.d \
./System/States/Cli/state_cli_erase_flash.d \
./System/States/Cli/state_cli_help.d \
./System/States/Cli/state_cli_main.d \
./System/States/Cli/state_cli_offload.d \
./System/States/Cli/state_cli_sense.d 


# Each subdirectory must supply rules for building sources it contributes
System/States/Cli/state_cli_calibrate.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_calibrate.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
System/States/Cli/state_cli_config.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_config.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
System/States/Cli/state_cli_erase_flash.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_erase_flash.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
System/States/Cli/state_cli_help.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_help.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
System/States/Cli/state_cli_main.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_main.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
System/States/Cli/state_cli_offload.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_offload.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
System/States/Cli/state_cli_sense.o: /home/nathan/Documents/DPF/stm32-avionics/System/States/Cli/state_cli_sense.cpp System/States/Cli/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../USB_DEVICE/App -I../USB_DEVICE/Target -I../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../System -I"/home/nathan/Documents/DPF/stm32-avionics/System" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Tasks" -I"/home/nathan/Documents/DPF/stm32-avionics/Utils" -I"/home/nathan/Documents/DPF/stm32-avionics/Devices" -I"/home/nathan/Documents/DPF/stm32-avionics/System/States/Cli" -I"/home/nathan/Documents/DPF/stm32-avionics/System/Filtering" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

