/*
 * board_config_types.h
 */

#ifndef DEVICES_BOARD_CONFIG_TYPES_H_
#define DEVICES_BOARD_CONFIG_TYPES_H_

#define RADIO_TI_TYPE_CC1120 1
#define RADIO_TI_TYPE_CC1200 2

#endif  // DEVICES_BOARD_CONFIG_TYPES_H_
