name: desktop_build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint job"

    steps:

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: clang-format-11 git python3 python3-venv
        version: 1.0

    - uses: actions/checkout@v3

    - name: Install things
      working-directory: ${{github.workspace}}
      run: |
        python3 --version
        python3 -m venv .venv/
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install cpplint

    - name: Run lint
      working-directory: ${{github.workspace}}
      run: |
        source .venv/bin/activate
        chmod -R +x ./ci/run_lint.sh
        ./ci/run_lint.sh


  build-linux:
    runs-on: ubuntu-latest
    name: "Build desktop flight software"

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: make g++ gcc
        version: 1.0

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Fetch tags.
    - name: Fetch tags
      run: git fetch --tags --force

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        touch CMakeListsPrivate.txt
        chmod -R +x ci/build_desktop.sh
        
    - name: Build desktop
      working-directory: ${{github.workspace}}
      run: ./ci/build_desktop.sh

    - uses: actions/upload-artifact@master
      with:
        name: desktop_sim
        path: ${{github.workspace}}/build/desktop_projects/desktop_sim/desktop_sim

  build-stm32:
    strategy:
      fail-fast: false
      matrix:
        include:
          - prj-rel-path: "stm32_projects/fcb_v0"
            prj-target: "fcb_v0"

    runs-on: ubuntu-latest
    container:
      image: mcm001/stm-actions:v1.0.0
    name: "Build flight software for ${{ matrix.prj-target }}"

    steps:
    - name: Check for dockerenv file
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Fetch tags.
    - name: Fetch tags
      run: git fetch --tags --force
    
    - name: Run build
      run: /entrypoint.sh ${{github.workspace}}/${{ matrix.prj-rel-path }} ${{ matrix.prj-target }} ${{ github.workspace }}

    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.prj-target }}
        path: ${{github.workspace}}/${{ matrix.prj-rel-path }}/Debug/*.elf

  release:
    needs: [build-linux, lint, build-stm32]
    runs-on: ubuntu-latest
    steps:
      # Download literally every single artifact. This also downloads client and docs,
      # but the filtering below won't pick these up (I hope)
      - uses: actions/download-artifact@v2

      - run: find

      # Push to dev release on pushes to master
      - uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'Dev'
          rm: true
          files: |
            **/*
        if: github.event_name == 'push'

      # Push to actual release, if tagged
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
